### ISSUE TITLE
jrsonnet 0.3.4 panics with TLS error on macos

### ISSUE THREAD

**Issue by akursell-wish** [CertainLach/jrsonnet#33]
This is using version 0.3.4 of `jrsonnet-darwin-amd64`.

```
$ echo '{}' | RUST_BACKTRACE=full jrsonnet -
{ }
thread '<unnamed>' panicked at 'cannot access a Thread Local Storage value during or after destruction: AccessError', /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/thread/local.rs:248:26
stack backtrace:
   0:        0x10920489f - __mh_execute_header
   1:        0x10917b6d0 - __mh_execute_header
   2:        0x109204076 - __mh_execute_header
   3:        0x109203ad2 - __mh_execute_header
   4:        0x1092033d2 - __mh_execute_header
   5:        0x109220549 - __mh_execute_header
   6:        0x1092204b8 - __mh_execute_header
   7:        0x109220460 - __mh_execute_header
   8:        0x10922a90f - __mh_execute_header
   9:        0x10922af05 - __mh_execute_header
  10:        0x1091e3427 - __mh_execute_header
  11:        0x10918811b - __mh_execute_header
  12:        0x109187423 - __mh_execute_header
  13:        0x1091db241 - __mh_execute_header
  14:        0x109220152 - __mh_execute_header
  15:     0x7fff20366555 - <unknown>
  16:     0x7fff20279f8b - <unknown>
Abort trap: 6
```

**Comment by CertainLach** [comment]
Eww... Something is trying to access TLS, while it is being dropped, when there is no Drop implementation in this crate

This drop is even occurs after writting output, so it must be TLS drop itself (https://github.com/CertainLach/jrsonnet/blob/master/cmds/jrsonnet/src/main.rs#L141)

I can't reproduce this on linux/windows build, so can you please try to compile jrsonnet in debug mode, and then provide backtrace with it?

Also, does it happens on 0.3.3 too?

**Comment by akursell-wish** [comment]
I tested a bunch of commits. https://github.com/CertainLach/jrsonnet/commit/695a2f8d51fa9a76e951a16f1cfb4e5c612c7b76 is the first to show the issue, but it disappears in https://github.com/CertainLach/jrsonnet/commit/a90b3d609f9a93f2ccf1b937a1e7ab55bdcdea7f and then reappears in https://github.com/CertainLach/jrsonnet/commit/814b019b0248e63ac2bbde4694bbc1cecbc8b73e. Here is a backtrace in debug mode from the latest commit:

```
 $ echo '{}' | RUST_BACKTRACE=full ../../target/debug/jrsonnet -
{ }
thread '<unnamed>' panicked at 'cannot access a Thread Local Storage value during or after destruction: AccessError', /Users/akursell/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:26
stack backtrace:
   0:        0x11034ba14 - std::backtrace_rs::backtrace::libunwind::trace::h2973c0f115cf39cb
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/../../backtrace/src/backtrace/libunwind.rs:100:5
   1:        0x11034ba14 - std::backtrace_rs::backtrace::trace_unsynchronized::h1a2874ce966099c0
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x11034ba14 - std::sys_common::backtrace::_print_fmt::h3b860fb438483fb1
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x11034ba14 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha0848bb2602b5d05
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:46:22
   4:        0x110369690 - core::fmt::write::h9f3ccac2ef682b93
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/fmt/mod.rs:1078:17
   5:        0x110348d96 - std::io::Write::write_fmt::h0a47673aab280496
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/io/mod.rs:1518:15
   6:        0x11034d7b9 - std::sys_common::backtrace::_print::h9c13ab471b84d474
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:49:5
   7:        0x11034d7b9 - std::sys_common::backtrace::print::h075217710b715efc
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:36:9
   8:        0x11034d7b9 - std::panicking::default_hook::{{closure}}::h850c6aaf5e80c2f5
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:208:50
   9:        0x11034d47d - std::panicking::default_hook::h037801299da6e1c6
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:227:9
  10:        0x11034de3b - std::panicking::rust_panic_with_hook::h76436d4cf7a368ac
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:593:17
  11:        0x11034d965 - std::panicking::begin_panic_handler::{{closure}}::h516c76d70abf04f6
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:499:13
  12:        0x11034be88 - std::sys_common::backtrace::__rust_end_short_backtrace::h653290b4f930faed
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:141:18
  13:        0x11034d8ca - rust_begin_unwind
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
  14:        0x110372def - core::panicking::panic_fmt::hde9134dd19c9a74f
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:92:14
  15:        0x110372cf5 - core::option::expect_none_failed::h686aad664d56bca5
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/option.rs:1268:5
  16:        0x1101d7e80 - core::result::Result<T,E>::expect::h59ec9f6ab627f356
                               at /Users/akursell/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:933:23
  17:        0x1101d0349 - std::thread::local::LocalKey<T>::with::hce90f8d8c284004a
                               at /Users/akursell/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  18:        0x1101d2090 - <jrsonnet_interner::IStr as core::ops::drop::Drop>::drop::h2eeac7b509dfefc5
                               at /Users/akursell/dev/jrsonnet/crates/jrsonnet-interner/src/lib.rs:45:4
  19:        0x110169375 - core::ptr::drop_in_place::h1e0d3b43ed456a4f
                               at /Users/akursell/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:175:1
  20:        0x11016a000 - core::ptr::drop_in_place::h9e779f7bed90efea
                               at /Users/akursell/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:175:1
  21:        0x11016a335 - core::ptr::drop_in_place::hcf9548e3f16067d8
                               at /Users/akursell/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:175:1
  22:        0x11016a5f2 - core::ptr::drop_in_place::hf283b40b9e943c68
                               at /Users/akursell/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:175:1
  23:        0x110169b3d - core::ptr::drop_in_place::h4218512e0c709ed5
                               at /Users/akursell/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:175:1
  24:        0x11016ac0f - <alloc::vec::Vec<T> as core::ops::drop::Drop>::drop::he1b324049bf3e354
                               at /Users/akursell/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/vec.rs:2595:13
  25:        0x11016a0d5 - core::ptr::drop_in_place::habfccbd38794cc77
                               at /Users/akursell/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:175:1
  26:        0x110169670 - core::ptr::drop_in_place::h377c152c5d6598d9
                               at /Users/akursell/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:175:1
  27:        0x110168db3 - core::ptr::drop_in_place::h0b6f3a7b42aedc60
                               at /Users/akursell/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:175:1
  28:        0x11016a9df - <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop::hf1b3cc570e1e08ad
                               at /Users/akursell/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/rc.rs:1221:17
  29:        0x110169c01 - core::ptr::drop_in_place::h53f035455d087ecf
                               at /Users/akursell/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:175:1
  30:        0x11016a6c5 - core::ptr::drop_in_place::hf9689fe453c14e20
                               at /Users/akursell/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:175:1
  31:        0x11016a0b9 - core::ptr::drop_in_place::ha9ae6b3102e70895
                               at /Users/akursell/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:175:1
  32:        0x1100ee0c9 - core::mem::drop::h6a5cfb962bed1274
                               at /Users/akursell/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/mem/mod.rs:882:24
  33:        0x110107e78 - std::thread::local::fast::destroy_value::h4c88eaa7a28a755d
                               at /Users/akursell/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:519:13
  34:        0x11035072c - std::sys::unix::thread_local_dtor::register_dtor::run_dtors::hfd12e3da9dc9b375
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys/unix/thread_local_dtor.rs:89:17
  35:     0x7fff20366555 - <unknown>
  36:     0x7fff20279f8b - <unknown>
fatal runtime error: failed to initiate panic, error 5
Abort trap: 6
```

**Comment by CertainLach** [comment]
Now i wonder how does this works on other platforms...
Thanks
