### ISSUE TITLE
Panic on evaluation of array

### ISSUE THREAD

**Issue by george-hopkins** [CertainLach/jrsonnet#69]
The evaluation of the snippet `[std.extVar('foo')]` results in a panic:

```text
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', jrsonnet/crates/jrsonnet-evaluator/src/lib.rs:136:47
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/panicking.rs:50:5
   3: std::thread::local::LocalKey<T>::with
   4: jrsonnet_evaluator::evaluate::evaluate
   5: jrsonnet_evaluator::evaluate::evaluate
   6: jrsonnet_evaluator::evaluate::evaluate_apply
   7: jrsonnet_evaluator::evaluate::evaluate
   8: <jrsonnet_evaluator::evaluate::evaluate::ArrayElement as jrsonnet_evaluator::val::LazyValValue>::get
   9: jrsonnet_evaluator::val::LazyVal::evaluate
  10: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
  11: jrsonnet_evaluator::integrations::serde::<impl core::convert::TryFrom<&jrsonnet_evaluator::val::Val> for serde_json::value::Value>::try_from
```

```rust
use std::convert::TryFrom;
use std::path::Path;

pub fn main() {
    let snippet = "[std.extVar('foo')]";
    let vm = jrsonnet_evaluator::EvaluationState::default();
    vm.with_stdlib();
    vm.settings_mut().ext_vars.insert("foo".into(), jrsonnet_evaluator::Val::Str("foo".into()));
    let value = vm.evaluate_snippet_raw(Path::new("snippet").into(), snippet.into()).unwrap();
    serde_json::Value::try_from(&value).unwrap();
}
```

Unfortunately, I'm not very familiar with code base and haven't been able to come up with a proper fix myself.

**Comment by CertainLach** [comment]
I should refactor this part of api somehow:
I use thread local for passing EvaluationState for stack trace collection, functions using stack (i.e code evaluation) needed to be executed via `run_in_state`:
```rs
let value = vm.run_in_state(|| {
    vm.evaluate_snippet_raw(Path::new("snippet").into(), snippet.into())
}).unwrap();
```

**Comment by george-hopkins** [comment]
Thank you for the hint! Going back to the example I used, it looks like I just forgot to copy the call to `run_in_state(...)`.
